language: cpp
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
    - gcc-5
    - g++-5
    - cmake
    - cmake-data
    - doxygen
os:
  - linux
compiler:
  - gcc
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ./runBiodynamoTests