language: cpp
sudo: required
dist: trusty
before-install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated gcc || brew upgrade gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc-5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install g++-5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen; fi
install:
  # link to newest compiler
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
    - gcc-5
    - g++-5
    - cmake
    - cmake-data
    - doxygen
os:
#  - linux
  - osx
compiler:
  - gcc
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ./runBiodynamoTests