language: cpp
sudo: required
#dist: trusty
install:
  - echo ${TRAVIS_OS_NAME} || true
  - brew update
  - brew outdated gcc || brew upgrade gcc || true
  - brew install gcc-5 || true
  - brew install g++-5 || true
  - then brew install doxygen || true
  # link to newest compiler
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
    - gcc-5
    - g++-5
    - cmake
    - cmake-data
    - doxygen
os:
#  - linux
  - osx
compiler:
  - gcc
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ./runBiodynamoTests